# Generated by Django 3.2.6 on 2021-08-31 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=1000)),
                ('level', models.IntegerField()),
                ('bio', models.CharField(max_length=1000)),
            ],
        ),
    ]
